[package]
name = "tree-sitter-nix"
description = "nix grammar for the tree-sitter parsing library"
version = "0.4.0"
keywords = ["incremental", "parsing", "nix"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/numtide/tree-sitter-nix"
edition = "2024"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "LICENSE",
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1.7"

[dev-dependencies]
tree-sitter = ">=0.26.0"

[build-dependencies]
cc = "1.0"
