{
  description = "tree-sitter-nix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }: (
    (flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (pkgs) lib;

        # package.json is the version of record; the other manifests
        # must agree with it (R1-032).
        version = (lib.importJSON ./package.json).version;

        # The CLI release that emitted the committed src/parser.c. A newer
        # generator rewrites parser.c and changes lexing (R1-011), so every
        # check that regenerates or compiles the grammar must use exactly
        # this version. Taken from parser.c's own header so the pin cannot
        # drift from the sources.
        generatorVersion =
          let
            header = builtins.head (lib.splitString "\n"
              (builtins.substring 0 200 (builtins.readFile ./src/parser.c)));
          in
          builtins.head (builtins.match ".*@generated by tree-sitter v([0-9.]+).*" header);

        # nixpkgs' tree-sitter is used as the generator; `generator-version`
        # below fails loudly when a nixpkgs bump moves it away from
        # generatorVersion, which is the moment to either regenerate
        # src/ deliberately or pin the CLI elsewhere.
        treeSitter = pkgs.tree-sitter;

        # Reference corpora for the differential oracle, at the revs pinned
        # in test/oracle/corpora.lock (KEY=VALUE, shared with the CI
        # scripts). The build sandbox has no network, so they are fetched
        # at evaluation time, pinned by rev and (for tarballs) NAR hash;
        # bump a hash together with its REV. Not fixed-output derivations
        # on purpose: snix's test fixtures spell out real /nix/store paths,
        # and Nix rejects a fixed-output result that references any store
        # path present on the builder.
        corporaLock = lib.pipe (builtins.readFile ./test/oracle/corpora.lock) [
          (lib.splitString "\n")
          (map (line: builtins.match "([A-Z_]+)=\"?([^\"]*)\"?" line))
          (builtins.filter (m: m != null))
          (map (m: lib.nameValuePair (builtins.head m) (builtins.elemAt m 1)))
          builtins.listToAttrs
        ];

        corpora = {
          nix = builtins.fetchTarball {
            url = "https://github.com/NixOS/nix/archive/${corporaLock.NIX_REV}.tar.gz";
            sha256 = "sha256-pCbuVA9LVjBY+j7XyTTWu2judbZa+yTdV9BKVUzqAdQ=";
          };
          rnix-parser = builtins.fetchTarball {
            url = "https://github.com/nix-community/rnix-parser/archive/${corporaLock.RNIX_REV}.tar.gz";
            sha256 = "sha256-GroET9+TyVppCYDFLEqgwJ9fig5GQfoCRGiLR5ZoHxU=";
          };
          # No GitHub mirror exists for snix; the commit id is the pin.
          snix = builtins.fetchGit {
            url = corporaLock.SNIX_URL;
            rev = corporaLock.SNIX_REV;
            shallow = true;
          };
        };

      in
      {
        checks =
          let
            # shellPackages = (pkgs.callPackage ./shell.nix { }).packages;

            # If the generated code differs from the checked in we need
            # to check in the newly generated sources.
            mkCheck = name: check: pkgs.runCommand name
              {
                inherit (self.devShells.${system}.default) nativeBuildInputs;
              } ''
              cp -rv ${self} src
              chmod +w -R src
              cd src

              ${check}

              touch $out
            '';

            # Oracle checks drive nix-instantiate and the tree-sitter CLI
            # from the Makefile targets under test/oracle/. nix needs a
            # writable state dir even for --parse, and must not touch the
            # (read-only) outer store, hence the dummy remote.
            mkOracleCheck = name: check: pkgs.runCommand name
              {
                nativeBuildInputs = [ treeSitter pkgs.nix pkgs.python3 ];
              } ''
              cp -r ${self} src
              chmod +w -R src
              cd src

              export HOME=$TMPDIR
              export NIX_STATE_DIR=$TMPDIR/nix
              export NIX_CONF_DIR=$TMPDIR/nixconf
              export NIX_REMOTE=dummy://
              export TREE_SITTER_LIBDIR=$TMPDIR/ts-lib

              ${check}

              touch $out
            '';

          in
          {
            build = self.packages.${system}.tree-sitter-nix;

            editorconfig = mkCheck "editorconfig" "editorconfig-checker";

            # The generator in this flake must be the one that emitted
            # src/parser.c; otherwise generated-diff compares apples to
            # oranges (R1-011).
            generator-version = pkgs.runCommand "generator-version"
              {
                nativeBuildInputs = [ treeSitter ];
                inherit generatorVersion;
              } ''
              got=$(tree-sitter --version | cut -d' ' -f2)
              if [ "$got" != "$generatorVersion" ]; then
                echo "src/parser.c was generated by tree-sitter v$generatorVersion but the flake provides v$got." >&2
                echo "Either regenerate src/ with v$got on purpose or keep nixpkgs' tree-sitter at v$generatorVersion." >&2
                exit 1
              fi
              touch $out
            '';

            # If the generated code differs from the checked in we need
            # to check in the newly generated sources.
            generated-diff = mkCheck "generated-diff" ''
              HOME=. npm run generate
              diff -r src/ ${self}/src
            '';

            treefmt = mkCheck "treefmt" "treefmt --no-cache --fail-on-change";

            oracle-precedence = mkOracleCheck "oracle-precedence" ''
              export NIXPKGS_PATH=${nixpkgs}
              make oracle
            '';

            oracle-differential = mkOracleCheck "oracle-differential" ''
              # fetch-corpora.sh symlinks these instead of downloading.
              export NIX_SRC=${corpora.nix}
              export RNIX_SRC=${corpora.rnix-parser}
              export SNIX_SRC=${corpora.snix}
              make differential
            '';

            # The flake's nixpkgs input is already in the store, so the
            # shape sample reads from it instead of a second checkout.
            oracle-shape = mkOracleCheck "oracle-shape" ''
              make shape-oracle NIXPKGS=${nixpkgs}
            '';

            rust-bindings =
              let
                cargo' = lib.importTOML ./Cargo.toml;
              in
              pkgs.rustPlatform.buildRustPackage {
                pname = cargo'.package.name;
                inherit (cargo'.package) version;
                src = self;
                cargoLock = {
                  lockFile = ./Cargo.lock;
                };
              };

            ocaml-bindings = pkgs.stdenv.mkDerivation {
              pname = "tree-sitter-nix-ocaml";
              inherit version;
              src = self;
              nativeBuildInputs = with pkgs.ocamlPackages; [
                ocaml
                dune_3
                findlib
              ];
              # tree-sitter is a `buildInputs` dep so the compiler
              # wrapper picks up its include/ and lib/ via NIX_CFLAGS_COMPILE
              # and NIX_LDFLAGS — letting `#include <tree_sitter/api.h>` and
              # `-ltree-sitter` resolve during the OCaml stubs compile + link.
              buildInputs = [ treeSitter ];
              buildPhase = ''
                runHook preBuild
                dune build bindings/ocaml
                dune runtest bindings/ocaml
                runHook postBuild
              '';
              installPhase = "touch $out";
            };

          } // lib.optionalAttrs (!pkgs.stdenv.isDarwin) {
            # Requires xcode
            node-bindings =
              let
                package' = lib.importJSON ./package.json;
              in
              pkgs.stdenv.mkDerivation {
                pname = package'.name;
                inherit (package') version;
                src = self;
                nativeBuildInputs = with pkgs; [
                  importNpmLock.hooks.npmConfigHook
                  nodejs
                  nodejs.passthru.python # for node-gyp
                  npmHooks.npmBuildHook
                  npmHooks.npmInstallHook
                  treeSitter
                ];
                npmDeps = pkgs.importNpmLock {
                  npmRoot = ./.;
                };
                # tree-sitter-cli (devDependency) has an install script that
                # downloads its binary; the sandbox has no network and this
                # check uses the Nix-provided CLI anyway, so leave dev
                # dependencies out and never run lifecycle scripts.
                npmInstallFlags = [ "--omit=dev" ];
                npmRebuildFlags = [ "--ignore-scripts" ];
                buildPhase = ''
                  runHook preBuild
                  # Generate parser using the Nix-provided tree-sitter
                  tree-sitter generate --abi 15
                  ${pkgs.node-gyp}/bin/node-gyp configure
                  ${pkgs.node-gyp}/bin/node-gyp build
                  runHook postBuild
                '';
                installPhase = "touch $out";
              };
          };

        packages.tree-sitter-nix = pkgs.callPackage ./default.nix { src = self; };
        packages.default = self.packages.${system}.tree-sitter-nix;
        devShells.default = pkgs.callPackage ./shell.nix { };

        formatter = pkgs.writeShellScriptBin "tree-sitter-nix-fmt" ''
          exec ${pkgs.treefmt}/bin/treefmt --config-file ${./treefmt.toml} "$@"
        '';

      }))
  );
}
